import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { ArrowRight, Check, ExternalLink, Play, ShieldCheck, Sparkles, WalletCards, Zap } from "lucide-react";
import { Link } from "wouter";

const features = [
  { icon: Sparkles, title: "AI-native DCA", text: "Configure a recurring strategy and let the agent coordinate execution through KeeperHub." },
  { icon: Zap, title: "Automated execution", text: "Designed around recurring on-chain execution rather than a static dashboard mockup." },
  { icon: ShieldCheck, title: "Auditable execution", text: "Execution records can be connected to the ERC-8004 audit trail for verifiable activity." },
  { icon: WalletCards, title: "KeeperHub wallet", text: "The application is designed around wallet, gas, and transaction infrastructure from KeeperHub." },
];

const timeline = [
  ["Strategy triggered", "12:00:01"],
  ["KeeperHub workflow started", "12:00:02"],
  ["Gas estimate calculated", "12:00:03"],
  ["Transaction submitted", "12:00:05"],
  ["Audit record created", "12:00:18"],
];

export default function Landing() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#050708] text-foreground">
      <header className="sticky top-0 z-50 border-b border-white/[0.08] bg-[#050708]/90 backdrop-blur-xl">
        <div className="mx-auto flex h-[72px] max-w-[1180px] items-center justify-between px-5 lg:px-8">
          <Link href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-300/35 bg-cyan-400/10 text-cyan-300 shadow-[0_0_26px_rgba(34,211,238,0.12)]"><ShieldCheck className="h-5 w-5" /></span><span><span className="block text-sm font-semibold tracking-wide">KGB</span><span className="block text-[10px] uppercase tracking-[0.25em] text-muted-foreground">KeeperHub Guard Bot</span></span></Link>
          <nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#product" className="transition-colors hover:text-foreground">Product</a><a href="#flow" className="transition-colors hover:text-foreground">How it works</a><a href="#security" className="transition-colors hover:text-foreground">Security</a><a href="#developers" className="transition-colors hover:text-foreground">Developers</a><a href="#faq" className="transition-colors hover:text-foreground">FAQ</a></nav>
          <div className="flex items-center gap-3"><a className="hidden text-sm text-muted-foreground transition-colors hover:text-foreground sm:inline-flex" href="https://github.com/lucylow/809890809809" target="_blank" rel="noreferrer">GitHub <ExternalLink className="ml-1 h-3.5 w-3.5" /></a><Button onClick={() => startLogin()} className="rounded-full bg-white px-5 text-black hover:bg-white/90">Launch App <ArrowRight className="ml-2 h-4 w-4" /></Button></div>
        </div>
      </header>
      <main>
        <section className="relative px-5 pb-24 pt-24 sm:pt-32"><div className="pointer-events-none absolute inset-x-0 top-0 -z-0 h-[560px] bg-[radial-gradient(circle_at_50%_20%,rgba(25,130,155,0.18),transparent_54%)]" /><div className="relative mx-auto max-w-[980px] text-center"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-cyan-300/25 bg-cyan-400/[0.08] px-4 py-2 text-xs font-medium uppercase tracking-[0.18em] text-cyan-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_#67e8f9]" />AI-native on-chain automation</div><h1 className="mx-auto mt-8 max-w-[900px] text-5xl font-semibold leading-[0.98] tracking-[-0.06em] text-white sm:text-7xl lg:text-[88px]">Your DeFi strategy.<span className="block bg-gradient-to-r from-cyan-300 via-white to-violet-300 bg-clip-text text-transparent">Automated on-chain.</span></h1><p className="mx-auto mt-8 max-w-[700px] text-base leading-8 text-muted-foreground sm:text-lg">KGB combines an AI-native DCA agent with KeeperHub infrastructure to automate recurring DeFi execution while keeping activity observable and auditable.</p><div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><Button onClick={() => startLogin()} size="lg" className="h-12 rounded-full bg-white px-7 text-black hover:bg-white/90">Start building <ArrowRight className="ml-2 h-4 w-4" /></Button><Link href="/app" className="inline-flex h-12 items-center rounded-full border border-white/15 bg-white/[0.04] px-7 text-sm font-medium text-white transition-colors hover:bg-white/[0.09]"><Play className="mr-2 h-4 w-4 fill-current" /> Explore the flow</Link></div><div className="mt-12 flex flex-wrap justify-center gap-x-8 gap-y-3 text-xs text-muted-foreground">{["KeeperHub infrastructure", "ERC-8004 audit trail", "Recurring execution"].map((item) => <span key={item} className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-cyan-300" />{item}</span>)}</div></div></section>
        <section id="product" className="mx-auto max-w-[1180px] scroll-mt-24 px-5 pb-28 lg:px-8"><div className="grid gap-5 md:grid-cols-2">{features.map(({ icon: Icon, title, text }) => <article key={title} className="group min-h-[260px] rounded-2xl border border-white/[0.1] bg-white/[0.025] p-8 transition-colors hover:border-cyan-300/35 hover:bg-cyan-300/[0.04]"><span className="flex h-12 w-12 items-center justify-center rounded-xl border border-cyan-300/20 bg-cyan-400/[0.08] text-cyan-300"><Icon className="h-5 w-5" /></span><h2 className="mt-9 text-2xl font-semibold tracking-tight text-white">{title}</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">{text}</p><Link href="/app" className="mt-7 inline-flex items-center text-sm text-cyan-300 transition-transform group-hover:translate-x-1">Learn more <ArrowRight className="ml-2 h-4 w-4" /></Link></article>)}</div></section>
        <section id="flow" className="border-y border-white/[0.08] bg-white/[0.015] px-5 py-28 lg:px-8"><div className="mx-auto grid max-w-[1180px] items-center gap-14 lg:grid-cols-2"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-violet-300">Live configuration</p><h2 className="mt-5 max-w-lg text-5xl font-semibold leading-[1.04] tracking-[-0.05em] text-white">See the strategy before it runs.</h2><p className="mt-6 max-w-lg text-base leading-8 text-muted-foreground">Give users a simple interface for defining recurring execution parameters while the backend handles the underlying workflow.</p><div className="mt-10 max-w-[520px]"><div className="flex items-center justify-between text-sm text-muted-foreground"><span>Investment amount</span><span className="text-white">$100 USDC</span></div><div className="mt-5 h-1.5 rounded-full bg-white/15"><div className="relative h-full w-[28%] rounded-full bg-cyan-300"><span className="absolute -right-2 -top-1.5 h-4 w-4 rounded-full border-2 border-cyan-200 bg-cyan-300" /></div></div><div className="mt-9 text-sm text-muted-foreground">Execution frequency</div><div className="mt-4 grid grid-cols-3 gap-2">{["Daily", "Weekly", "Monthly"].map((item) => <span key={item} className={`rounded-xl border px-4 py-3 text-center text-sm ${item === "Weekly" ? "border-cyan-300/50 bg-cyan-300/10 text-cyan-200" : "border-white/10 bg-white/[0.03] text-muted-foreground"}`}>{item}</span>)}</div></div></div><div className="rounded-2xl border border-white/[0.12] bg-[#090d0f] p-7 shadow-2xl shadow-cyan-950/20"><div className="flex items-start justify-between border-b border-white/[0.08] pb-6"><div><p className="text-sm text-muted-foreground">Strategy preview</p><h3 className="mt-2 text-2xl font-semibold text-white">ETH DCA Agent</h3></div><span className="rounded-full bg-emerald-300/10 px-3 py-1.5 text-xs font-medium text-emerald-300">Ready</span></div><div className="divide-y divide-white/[0.07]">{[['Amount', '100 USDC'], ['Frequency', 'Weekly'], ['Asset', 'ETH / WETH'], ['Execution', 'KeeperHub'], ['Audit', 'ERC-8004']].map(([label, value]) => <div key={label} className="flex justify-between py-5 text-sm"><span className="text-muted-foreground">{label}</span><span className="text-white">{value}</span></div>)}</div><div className="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.06] p-5"><div className="flex gap-3"><Sparkles className="mt-0.5 h-5 w-5 text-cyan-300" /><div><h4 className="font-medium text-white">Agent status</h4><p className="mt-1 text-sm leading-6 text-muted-foreground">Strategy configured. The agent can evaluate the next scheduled execution.</p></div></div></div><Link href="/app" className="mt-5 flex h-12 items-center justify-center rounded-full bg-white text-sm font-semibold text-black transition-colors hover:bg-white/90">Configure strategy <ArrowRight className="ml-2 h-4 w-4" /></Link></div></div></section>
        <section id="security" className="px-5 py-28 lg:px-8"><div className="mx-auto grid max-w-[1180px] items-center gap-14 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-emerald-300">Execution</p><h2 className="mt-5 max-w-lg text-5xl font-semibold leading-[1.04] tracking-[-0.05em] text-white">Make every execution visible.</h2><p className="mt-6 max-w-lg text-base leading-8 text-muted-foreground">Understand what happened, when it happened, which asset was involved, and where the transaction can be verified.</p></div><div className="rounded-2xl border border-white/[0.12] bg-[#090d0f] p-6 sm:p-8">{timeline.map(([label, time], index) => <div key={label} className="flex gap-4"><div className="relative flex w-5 shrink-0 justify-center"><span className="z-10 mt-1.5 h-3.5 w-3.5 rounded-full border-2 border-cyan-300 bg-[#090d0f] shadow-[0_0_12px_rgba(34,211,238,0.7)]" />{index < timeline.length - 1 && <span className="absolute top-5 h-full w-px bg-cyan-300/25" />}</div><div className="flex flex-1 justify-between border-b border-white/[0.07] pb-6 pt-0 text-sm"><span className="text-muted-foreground">{label}</span><span className="font-mono text-xs text-muted-foreground/70">{time}</span></div></div>)}</div></div></section>
        <section id="developers" className="border-t border-white/[0.08] px-5 py-24 text-center lg:px-8"><p className="text-xs font-medium uppercase tracking-[0.2em] text-cyan-300">Built for operators</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">Ship a strategy. Keep the execution observable.</h2><p className="mx-auto mt-6 max-w-2xl leading-8 text-muted-foreground">Connect the frontend experience to the KeeperHub agent, configure safety limits, and inspect every result through the dashboard.</p><Button onClick={() => startLogin()} size="lg" className="mt-9 rounded-full bg-white px-7 text-black hover:bg-white/90">Launch KeeperHub <ArrowRight className="ml-2 h-4 w-4" /></Button></section>
      </main>
      <footer id="faq" className="border-t border-white/[0.08] px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-4 text-xs text-muted-foreground sm:flex-row"><span>© 2026 KeeperHub Guard Bot</span><span>AI-native DCA · ERC-8004 audit trail · Base-ready workflows</span></div></footer>
    </div>
  );
}
